# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.TextField()),
                ('scoring_data', models.TextField()),
                ('duration', models.DurationField()),
                ('submission_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LatLngBounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.FloatField()),
                ('north', models.FloatField()),
                ('south', models.FloatField()),
                ('west', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour_map_image', models.BinaryField()),
                ('contour_map_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maps.LatLngBounds')),
                ('display_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maps.LatLngBounds')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_duration', models.DurationField()),
                ('type', models.TextField()),
                ('statement_data', models.TextField()),
                ('reference_data', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('map_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.MapArea')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_duration', models.DurationField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.QuestionSet')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='answerset',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.QuestionSet'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.AnswerSet'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_set_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.QuestionSetMember'),
        ),
    ]
