# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170101_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsetmember',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionsetmember',
            name='question_set',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_set_member',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.QuestionSet'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='question_ids',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.QuestionSet'),
        ),
        migrations.DeleteModel(
            name='QuestionSetMember',
        ),
    ]
