# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='scoring_data',
            field=models.TextField(null=True),
        ),
    ]
