# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_maparea_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maparea',
            name='contour_map_image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='maparea',
            name='contour_map_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maps.LatLngBounds'),
        ),
    ]
